### ISSUE TITLE
Common labels - ARM parameter

### ISSUE THREAD

**Issue by jmagosta** [krishnand/mlsdistcomp#1]
Resource group name, DNS prefix and App name can all be defaulted to one choice.  This is chosen when running the AAD cmd line - so remove the DNS prefix entry in the ARM template.

**Comment by krishnand** [comment]
Defaulting enforced as of - https://github.com/krishnand/mlsdistcomp/commit/8cf5376849f5d18a53226a66a15aa3f8ca2a45d9
