### ISSUE TITLE
Linux VM account name  - ARM template entry

### ISSUE THREAD

**Issue by jmagosta** [krishnand/mlsdistcomp#2]
Change system user name from admin to default to "distcomp" = and have the user choose a strong password.   (Port 22 will not be open by default or exposed via public IP).

**Comment by krishnand** [comment]
Everything is being defaulted to the resource group name as of this commit - https://github.com/krishnand/mlsdistcomp/commit/8cf5376849f5d18a53226a66a15aa3f8ca2a45d9
